name: Java CI with Maven

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn clean install -DskipTests

    - name: Deploy to VPS
      env:
        SERVER_HOST: ${{ secrets.SERVER_HOST }}
        SERVER_PORT: ${{ secrets.SERVER_PORT }}
        SERVER_USERNAME: ${{ secrets.SERVER_USERNAME }}
      run: |
        echo "Creando directorio de logs (si no existe)..."
        ssh -p $SERVER_PORT $SERVER_USERNAME@$SERVER_HOST "mkdir -p /var/www/C6-metas-financieras/logs"

        echo "Matando proceso anterior (si existe)..."
        ssh -p $SERVER_PORT $SERVER_USERNAME@$SERVER_HOST "\
          PID=\$(pgrep -f goals-0.0.1-SNAPSHOT.jar); \
          if [ ! -z \"$PID\" ]; then \
            echo \"PID encontrado: $PID. Matando proceso...\"; \
            kill -9 $PID; \
          else \
            echo 'No se encontró el proceso para matar'; \
          fi \
        "

        echo "Copiando el nuevo JAR..."
        scp -P $SERVER_PORT target/goals-0.0.1-SNAPSHOT.jar $SERVER_USERNAME@$SERVER_HOST:/var/www/C6-metas-financieras/

        echo "Dando permisos de ejecución al JAR..."
        ssh -p $SERVER_PORT $SERVER_USERNAME@$SERVER_HOST "chmod +x /var/www/C6-metas-financieras/goals-0.0.1-SNAPSHOT.jar"

        echo "Iniciando la aplicación en segundo plano con las variables de entorno..."
        ssh -p $SERVER_PORT $SERVER_USERNAME@$SERVER_HOST "\
          export \$(grep -v '^#' /var/www/C6-metas-financieras/.env | xargs) && \
          nohup java -jar /var/www/C6-metas-financieras/goals-0.0.1-SNAPSHOT.jar > /var/www/C6-metas-financieras/logs/output.log 2>&1 & \
        "

        echo "Verificando que la aplicación se está ejecutando..."
        ssh -p $SERVER_PORT $SERVER_USERNAME@$SERVER_HOST "pgrep -f goals-0.0.1-SNAPSHOT.jar && echo 'Aplicación iniciada correctamente' || (echo 'Error al iniciar la aplicación' && exit 1)"

        echo "Revisando logs para diagnosticar errores..."
        ssh -p $SERVER_PORT $SERVER_USERNAME@$SERVER_HOST "tail -n 50 /var/www/C6-metas-financieras/logs/output.log"

    - name: Cleanup
      if: failure()
      run: echo "La implementación falló. Revisa los logs anteriores para más detalles."
