name: Java CI with Maven
on:
  push:
    branches: [ "main", "feature/github_action" ]
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build and test with Maven
        run: |
          mvn clean package
          ls -l target/*.jar  # Verifica que el JAR se genere correctamente

      - name: Initialize SSH and Trust Host
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p ${{ secrets.SERVER_PORT }} -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: Setting up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SERVER_KEY }}

      - name: Crear archivo .env en el servidor
        run: |
          echo "JDBC_DATABASE_URL=${{ secrets.JDBC_DATABASE_URL }}" > ~/.env
          echo "JDBC_DATABASE_USERNAME=${{ secrets.JDBC_DATABASE_USERNAME }}" >> ~/.env
          echo "JDBC_DATABASE_PASSWORD=${{ secrets.JDBC_DATABASE_PASSWORD }}" >> ~/.env
          echo "SECURITY_USER_NAME=${{ secrets.SECURITY_USER_NAME }}" >> ~/.env
          echo "SECURITY_USER_PASSWORD=${{ secrets.SECURITY_USER_PASSWORD }}" >> ~/.env
          echo "SWAGGER_UI_PATH=${{ secrets.SWAGGER_UI_PATH }}" >> ~/.env
          echo "SERVER_PORT=${{ secrets.SERVER_PORT }}" >> ~/.env
          echo "IA_API_KEY=${{ secrets.IA_API_KEY }}" >> ~/.env
          echo "IA_API_URL=${{ secrets.IA_API_URL }}" >> ~/.env
          echo "IA_MODEL=${{ secrets.IA_MODEL }}" >> ~/.env
          echo "IA_MAX_TOKENS=${{ secrets.IA_MAX_TOKENS }}" >> ~/.env
          echo "IA_MAX_TEMPERATURE=${{ secrets.IA_MAX_TEMPERATURE }}" >> ~/.env
          echo "IA_TOP_P=${{ secrets.IA_TOP_P }}" >> ~/.env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> ~/.env
          echo "JWT_EXPIRATION=${{ secrets.JWT_EXPIRATION }}" >> ~/.env
          echo "JWT_REFRESH=${{ secrets.JWT_REFRESH }}" >> ~/.env
          scp -P ${{ secrets.SERVER_PORT }} ~/.env ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }}:/var/www/C6-metas-financieras/.env

      - name: Deploy to VPS
        run: |
          set -e  # Detener el script si algún comando falla

          echo "Creando directorio de logs (si no existe)..."
          ssh -p ${{ secrets.SERVER_PORT }} ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} "mkdir -p /var/www/C6-metas-financieras/logs"

          echo "Matando proceso anterior (si existe)..."
          ssh -p ${{ secrets.SERVER_PORT }} ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} "\
          PID=\$(pgrep -f goals-0.0.1-SNAPSHOT.jar) && echo \"PID encontrado: \$PID\" || echo 'No se encontró el proceso para matar' \
          "

          echo "Copiando el nuevo JAR..."
          scp -P ${{ secrets.SERVER_PORT }} target/goals-0.0.1-SNAPSHOT.jar ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }}:/var/www/C6-metas-financieras/

          echo "Copiando el archivo .env al servidor..."
          scp -P ${{ secrets.SERVER_PORT }} .env ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }}:/var/www/C6-metas-financieras/

          echo "Verificando que el JAR y .env se copió correctamente..."
          ssh -p ${{ secrets.SERVER_PORT }} ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} "ls -l /var/www/C6-metas-financieras"

          echo "Dando permisos de ejecución al JAR..."
          ssh -p ${{ secrets.SERVER_PORT }} ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} "chmod +x /var/www/C6-metas-financieras/goals-0.0.1-SNAPSHOT.jar"

          echo "Iniciando la aplicación en segundo plano con las variables de entorno..."
          ssh -p ${{ secrets.SERVER_PORT }} ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} "\
          source /var/www/C6-metas-financieras/.env && nohup java -jar /var/www/C6-metas-financieras/goals-0.0.1-SNAPSHOT.jar > /var/www/C6-metas-financieras/logs/output.log 2>&1 & \
          "

          echo "Verificando que la aplicación se está ejecutando..."
          ssh -p ${{ secrets.SERVER_PORT }} ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} "pgrep -f goals-0.0.1-SNAPSHOT.jar"

          echo "Deploy completed"
